### ISSUE TITLE
i2pd outproxy - how to turn this off??

### ISSUE THREAD

**Issue by TimmyBoi155** [PurpleI2P/i2pd-qt#109]
I do not want my browser to connect to anything that isn't in i2p network!

How do I turn this off? There is no off button in the QT gui? 

So how can I turn this off? This is very bad opsec!

Thanks

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
> My config does not have any outproxy defined at all under this section. So why is it still using an outproxy?

It doesn't use httpproxy outproxy in this case, adding a boolean option to turn off the empty outproxy would be redundant.

> yet it was still doing outproxy.

It wasn't. How do you make sure that it was doing it?

**Comment by TimmyBoi155** [comment]
@nonlin-lin-chaos-order-etc-etal 

okay looks like there is a problem with my setup. I am using a modified tor browser, and apparently clicking on a clearnet site from an i2p site will actually route the connection through configured socks proxy in the about:config, even if you're using the 4444 i2p http proxy

for those to whom it might be helpful, this is the fix:

make sure to set network.proxy.socks to empty string and network.proxy.socks_port to 0, where it originally is 9150. If you do not, clicking on clearnet links from i2p sites will connect to the site through the 9150 port tor proxy. Although, this behavior might actually be useful to you, but be aware that your Referrer origin, the i2p site, will be visible to the clearnet site you connect to.

**Comment by TimmyBoi155** [comment]
My apologies to everyone in this issue, thank you for being patient with my lack of wisdom and intelligence @nonlin-lin-chaos-order-etc-etal @Vort @orignal
