### ISSUE TITLE
Typing pointer jump to "Name" field after entering every character/number within any other field when adding new tunnel !!

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd-qt#26]
Hi. I discover this very morbid GUI bug !!! 

To reproduce it, do the following:

1) open GUI,
2) Tunnel setting,
3) add new tunnel (client or server),
4) enter the name. This is okay,
5) now set typing pointer within any next field & try to enter it's value. You will see that just by typing any character or number (just one), then the typing pointer will jump to field of "Name" !!!

To overcome this bug user need to re-set typing pointer again to intended field after every time enter a character or a number in any next field following "Name" field & remain repeat this till finish all parameters !!! This is very very morbid !! Kindly give it attention !

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 please update your flathub package website.i2pd.i2pd, it's fixed, I just confirmed.

@r4sas or @Nokia808 please close this issue.
