### ISSUE TITLE
Compilation in Linux

### ISSUE THREAD

**Issue by ghost** [PurpleI2P/i2pd-qt#53]
Первоначальная инструкция (реальное положение дел немного изменилось, i2pd теперь надо клонировать самому):
https://i2pd.readthedocs.io/en/latest/devs/building/qt-desktop-gui/

Мои дополнения 2021 года (проверено в Ubuntu 16.04, Qt 5.5.1):
Qt5 из Debian 8 (Jessie) уже слишком стар.
Если не указаны пути, предполагается, что это домашняя папка `/home/user`

установка сборочных зависимостей:
`sudo apt install build-essential binutils gcc g++ make cmake git fakeroot devscripts dh-apparmor libboost-all-dev libboost-date-time-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libcrypto++-dev libwebsocketpp-dev libssl-dev libminiupnpc-dev zlib1g-dev qt5-default libqt5gui5 qt5-qmake qtcreator`

клонирование:
```
git clone https://github.com/PurpleI2P/i2pd.git
git clone https://github.com/PurpleI2P/i2pd-qt.git
```
скопировать содержимое каталога i2pd (кроме .git) в i2pd-qt/src/i2pd

**ИЛИ**

```
git clone --recursive https://github.com/PurpleI2P/i2pd-qt.git
```

но в этом случае модуль src/i2pd будет последней **релизной** версии, а **не самой последней** git версии.

**-----СБОРКА В QTCREATOR------**
Проверка параметров:
В Qt Creator Инструменты - Параметры - Сборка и запуск - Комплекты:
Профиль Qt 5.x.x
`/usr/bin/cmake`
Инструменты - Параметры - Сборка и запуск - Qt Versions:
Qt 5.x.x в PATH (qt5) `/usr/lib/x86_64-linux-gnu/qt5/bin/qmake` должно быть без ошибок

Сборка:
открыть в Qt Creator `i2pd-qt/i2pd_qt.pro`
подождать разбора файлов
снять галочку с "Отладка"
кнопка "Настроить проект"
подождать разбора файлов
вкладка "Проекты"
Изменить конфигурацию сборки: Отладка - Выпуск
можно также проверить настройки Desktop - Сборка - Запуск - Сборка
закрыть лишние приложения, требуется много памяти (много потребляет сам qt creator)
Слева внизу нажать на значок молотка "Собрать проект i2pd_qt" Ctrl+B
Или "Сборка - Собрать всё" Ctrl+Shift+B
Открыть консоль сборки 4

выходной файл будет здесь `/home/user/build-i2pd_qt-Desktop-Release/i2pd_qt` (среди кучи других, отсортируйте по типу)
`strip --strip-unneeded /home/user/build-i2pd_qt-Desktop-Release/i2pd_qt` (уменьшение размера)
скопировать его в любое место, например в PATH `/home/user/.local/bin`
переименовать по желанию, остальные файлы не нужны

ярлык запуска можно взять отсюда `/home/user/i2pd-qt/contrib/website.i2pd.i2pd.desktop` (и поместить в `/home/user/.local/share/applications`)
иконки (их указать в файле .desktop):
`/home/user/i2pd-qt/contrib/icons/128x128/website.i2pd.i2pd.png`
`/home/user/i2pd-qt/src/resources/icons/mask.ico`
`/home/user/i2pd-qt/src/resources/images/icon.png`
**-----СБОРКА В QTCREATOR------**

**ИЛИ**

**-----СБОРКА В QMAKE (НЕ ПРОВЕРЕНО)------**
вместо Qt Creator можно использовать консольный qmake:
```
cd i2pd-qt
qmake i2pd_qt.pro
make USE_UPNP=yes
sudo make install
```
Остальное см. выше
**-----СБОРКА В QMAKE (НЕ ПРОВЕРЕНО)------**

профиль находится в `/home/user/.i2pd`

настройка браузера:
настройка http://127.0.0.1:7070/
http(s) прокси 127.0.0.1:4444 (рекомендуется, в нем работают outproxy и подсказки)
socks proxy 127.0.0.1:4447

maximize не работает

включенные по умолчанию службы:
HTTP Proxy	Enabled
SOCKS Proxy	Enabled
BOB		Disabled
SAM		Enabled
I2CP		Disabled
I2PControl	Disabled

настройка логов:
Logs destination (stdout, file, syslog)
Logs level (debug, info, warn, error, none)

log=syslog
loglevel=none
logclftime=false

i2pd.conf править только при закрытом i2pd-qt, иначе изменения сбрасываются
i2pd-qt запускать от обычного пользователя (без sudo), не от root. Не используйте sudo для графических приложений, это повредит права профиля `~/.i2pd` и других файлов

**UPD:** Для запуска скомпилированного бинарника на новой системе достаточно установить следующие пакеты/зависимости, на примере Ubuntu 20.04:

`sudo apt install libssl1.1 libcrypto++6 zlib1g libqt5gui5 libqt5core5a libqt5widgets5 libminiupnpc17 libboost-date-time1.71.0 libboost-filesystem1.71.0 libboost-program-options1.71.0 libboost-system1.71.0`

Как видите, они не упоминаются в разделе "установка сборочных зависимостей" выше, хотя, конечно же, тоже нужны. Вместо них там -dev версии. Просто, -dev версии по зависимостям подтягивают эти самые пакеты. А не указаны они для упрощения и потому что основные пакеты часто релизноспецифичны.
Эти номера версий соответствуют Ubuntu 20.04. Для других убунт можно свериться [здесь](https://packages.ubuntu.com/) или в пакетном менеджере Synaptic.
-dev версии и компиляторы для простого запуска не нужны.

Проверить зависимости бинарника можно такой командой:
`readelf -d /home/user/build-i2pd_qt-Desktop-Release/i2pd_qt`
А насколько они удовлетворяются командой ldd (она также показывает зависимости зависимостей, в отличии от readelf):
`ldd /home/user/build-i2pd_qt-Desktop-Release/i2pd_qt`

**Comment by r4sas** [comment]
Не правильно клонируете, если цель - собрать i2pd-qt. Нужно вызывать другую команду:
`git clone --recursive https://github.com/PurpleI2P/i2pd-qt.git`

**Comment by artenaki** [comment]
@r4sas спасибо, не доглядел.

Кто-нибудь пробовал [компилировать](https://i2pd.readthedocs.io/en/latest/devs/building/qt-desktop-gui/) в Msys2 для XP? Компилировать надо в Win7+, но чтобы заработало потом на XP, видимо придется заменить [mingw-w64-qt5-static](https://packages.msys2.org/base/mingw-w64-qt5-static) 5.15 на Qt 5.6 с сайта Qt. Набросал бы кто-нибудь инструкцию, а я попробую. Можно создать новую тему.
Возможно, еще какие-то либы из репозитория Msys2 несовместимы с XP. Ведь это роллинг, постоянно обновляют. Уже python 3.9 не совместим даже с Win7.
Инструкцию по установке Msys2 i686 можно посмотреть, например, [здесь](http://forum.oszone.net/thread-347851.html).

Может быть заменить Msys2 на что-то более стабильное и неизменное? Например, на Visual Studio <= 2019 (с XP тулчайном) + скачать сборочные библиотеки самому. Хотя, Студия очень жирная.
В идеале хотелось бы скомпилить на XP для XP с минимальной установкой всякого. Может быть в старом QtCreator на XP + отдельный mingw. Я в этом вообще не  шарю.

**Comment by r4sas** [comment]
Про qt версию для XP забудьте. Я даже не собираюсь пытаться тянуть поддержку. А чисто i2pd для него я и так собираю - смотрите в релизы.

**Comment by artenaki** [comment]
> Нужно вызывать другую команду:
> git clone --recursive

Тогда i2pd будет релизный, а не самый последний гитовский. И если i2pd-qt забросят, то версия застрянет в развитии.
Немного обновил и дополнил инструкцию.

@r4sas а вы acetone?
