### ISSUE TITLE
unable to use this giu on win 10 home 64

### ISSUE THREAD

**Issue by p060477** [PurpleI2P/i2pd-qt#91]
hi, how to be able to use this gui in win 10 home 64 desktop pc...??
is there a way to be able to have it working...??
thxs so mcu in adv
cheers

**Comment by r4sas** [comment]
It is not recommended to use i2pd-qt on windows, so there is no way.

**Comment by p060477** [comment]
pls so make _a gui_   **working fine** also for windows pls
thxs so much
cheers
